### ISSUE TITLE
High CPU load when doing teleop

### ISSUE THREAD

**Issue by jim-v** [UbiquityRobotics/bus_server#1]
Need to look at queuing of `/cmd_vel`.

DOD: CPU load < 10% when doing teleop.

**Comment by rohbotics** [comment]
@jim-v Can you post which isinstance calls you found were slow?

**Comment by waynegramlich** [comment]
I would recommend a simple global replace of "assert isinstance" => "#assert isisntance".  Then see if that makes a difference.

**Comment by jim-v** [comment]
With `assert isinstance`  7.3% CPU when idle, 20% when receiving twists at 20Hz.
Without, it's about the same.  Commenting out some print statements reduced the CPU to 12% when receiving twists, so that looks like a better optimization.   When I tried this experiment before, I disabled asserts and prints, and didn't get around to following up to see which was the culprit.

**Comment by rohbotics** [comment]
I think the print output is already way too high for being in general info and not a debugging thing. 

I think we should use `rospy.logdebug` for all the 'Poll' prints, that way we can enable them if desired using rqt_logger_level.

**Comment by waynegramlich** [comment]
Just to be clear.  This code base evolved from the ROS Arduino Bridge written by Patrick Goebel.  I am not surprised that it can be made more efficient.
